import type { TSESLint } from "@typescript-eslint/utils";
import { mkdirp } from "mkdirp";
import path from "path";
import util from "util";
import { GeneratorContext, GeneratorOptions, setupContext } from "./context.js";
import { findPlugins, type Plugin } from "./find-plugins.js";
import { generateRuleTypeFiles } from "./generate-rule-type-files.js";
import { formatText, toPascalCase } from "./text-utils.js";

const debug = util.debuglog("generate-types");

export type RuleModule = TSESLint.RuleModule<string, unknown[]>;
export type RuleRecord = Record<string, RuleModule>;

function isRuleDeprecated(rule: {
  meta: { deprecated?: boolean };
}): rule is { meta: { deprecated: true } } {
  return rule.meta.deprecated === true;
}

/**
 * Coerce an eslint rule into an object if it is a function-defined rule by
 * assigning to `rule.meta.create` and setting default values for other
 * expected properties. If it is already an object, it will be returned as is.
 *
 * Function rule definitions are technically deprecated by Eslint but
 * its still possible we could import one.
 */
function coerceRuleObject(
  rule: RuleModule | TSESLint.RuleCreateFunction
): RuleModule {
  if (typeof rule === "function") {
    return {
      defaultOptions: [],
      meta: {
        messages: {},
        schema: {},
        type: "suggestion",
      },
      create: rule,
    };
  }
  return rule;
}

function normalizeRules(initialRules: Plugin["rules"]): RuleRecord {
  const ruleEntries = Object.entries(initialRules ?? {})
    .map(([name, rule]) => [name, coerceRuleObject(rule)] as const)
    .filter(([, rule]) => !isRuleDeprecated(rule));

  return Object.fromEntries(ruleEntries);
}

async function generatePluginIndexFile(
  context: GeneratorContext,
  plugin: Plugin,
  rules: RuleRecord
) {
  const ruleNames = Object.keys(rules).map((ruleName) => ({
    name: ruleName,
    safeName: toPascalCase(ruleName.replace(`${plugin.name}/`, "")),
  }));

  const rulePrefix = plugin.name === "eslint" ? "" : `${plugin.name}/`;

  const filePath = path.resolve(context.outDir, plugin.name, "index.ts");

  const textContent = formatText(`
    ${context.autoGeneratedNote}
    ${ruleNames
      .map(
        (rule) =>
          `import type { ${rule.safeName} } from '../${plugin.name}/${rule.name}.js';`
      )
      .join("\n")}

    /**
     * ${plugin.module} Rules
     */
    export interface ${toPascalCase(plugin.name)} {
      ${ruleNames
        .map((rule) => `'${rulePrefix}${rule.name}': ${rule.safeName};`)
        .join("\n")}
    }
  `);

  context.write(filePath, textContent);

  debug("Wrote types for ", plugin.module);
}

async function processPlugin(context: GeneratorContext, plugin: Plugin) {
  debug(`processing plugin \`%s\``, plugin.module);

  if (!plugin.rules) {
    debug(`no rules found. skipping...`);
    return;
  }

  const rules = normalizeRules(plugin.rules);

  const pluginDir = path.resolve(context.outDir, plugin.name);

  await mkdirp(pluginDir);

  await generateRuleTypeFiles(context, rules, pluginDir);

  await generatePluginIndexFile(context, plugin, rules);
}

export async function generateRuleTypes(
  options: GeneratorOptions
): Promise<void> {
  const context = setupContext(options);
  const plugins = findPlugins();

  for await (const plugin of plugins) {
    processPlugin(context, plugin);
  }

  console.info("Done!");
}
